GDJ58-2/Bakery

- src/main/java/vo/GoodsCategory.java
> [조영우] vo GoodsCateogry 수정

- src/main/java/controller/question/AddQuestionController.java
- src/main/java/controller/question/ModifyQuestionController.java
- src/main/java/controller/question/QuestionListController.java
- src/main/java/controller/question/QuestionOneController.java
- src/main/java/controller/question/RemoveQuestionController.java
- src/main/java/dao/QuestionDao.java
- src/main/java/service/QuestionService.java
- src/main/webapp/WEB-INF/view/admin/goods/addGoods.jsp
- src/main/webapp/WEB-INF/view/admin/goods/modifyGoods.jsp
- src/main/webapp/WEB-INF/view/question/addQuestion.jsp
- src/main/webapp/WEB-INF/view/question/modifyQuestion.jsp
- src/main/webapp/WEB-INF/view/question/questionList.jsp
- src/main/webapp/WEB-INF/view/question/questionOne.jsp
- src/main/webapp/WEB-INF/view/question/removeQuestion.jsp
> [조영우] question 문의 CRUD 생성

- src/main/java/vo/Orders.java
- src/main/webapp/db/shop.sql
[조영우] vo Orders 수정 / db shop.sql 추가
> [조영우] vo Orders 수정 / db shop.sql 추가

- src/main/java/dao/SiteCounterDao.java
- src/main/java/filter/EncodingFilter.java
- src/main/java/listener/BootListener.java
- src/main/java/listener/CounterListener.java
- src/main/java/service/SiteCounterService.java
> [조영우] filter / listener 생성

- src/main/java/dao/SiteCounterDao.java
> [조영우] SiteCounter dao 수정

- src/main/java/controller/orders/OrdersListController.java
- src/main/java/controller/orders/OrdersOneController.java
- src/main/java/dao/OrdersDao.java
- src/main/java/dao/SiteCounterDao.java
- src/main/java/filter/EncodingFilter.java
- src/main/java/listener/CounterListener.java
- src/main/java/service/OrdersService.java
- src/main/java/service/SiteCounterService.java
- src/main/webapp/WEB-INF/view/orders/ordersList.jsp
- src/main/webapp/WEB-INF/view/orders/ordersOne.jsp
[조영우] filter 수정 / listener Site CounterService 생성 / orders CRUD GET 주문
> [조영우] filter 수정 / listener Site CounterService 생성 / orders CRUD GET 주문

- src/main/java/controller/pointHistory/PointHistoryListController.java
- src/main/java/dao/OrdersDao.java
- src/main/java/dao/PointHistoryDao.java
- src/main/java/service/PointHistoryService.java
- src/main/webapp/WEB-INF/view/orders/ordersList.jsp
- src/main/webapp/WEB-INF/view/pointHistory/pointHistoryList.jsp
> [조영우] pointHistory GET 리스트 구현

- src/main/java/controller/pointHistory/PointHistoryListController.java
[조영우] PointHistory Controller 수정
> [조영우] PointHistory Controller 수정

- src/main/java/controller/cart/ModifyCartController.java
- src/main/java/controller/cart/selectCartListController.java
- src/main/java/controller/orders/AddOrdersController.java
- src/main/java/controller/orders/AddOrdersListController.java
- src/main/java/controller/orders/ModifyOrdersController.java
- src/main/java/dao/CartDao.java
- src/main/java/dao/OrdersDao.java
- src/main/java/service/CartService.java
- src/main/webapp/WEB-INF/view/cart/cartList.jsp
- src/main/webapp/WEB-INF/view/orders/addOrders.jsp
- src/main/webapp/WEB-INF/view/orders/modifyOrders.jsp
[이가은] addOrders 다중 주문 기능 추가,cartList 뷰 수정, cart테이블 update
> [이가은] addOrders 다중 주문 기능 추가,cartList 뷰 수정, cart테이블 update

- src/main/java/controller/customerAddress/CustomerAddressListController.java
- src/main/java/controller/customerAddress/ModifyCustomerAddressController.java
- src/main/java/controller/question/ModifyQuestionController.java
- src/main/java/dao/CustomerAddressDao.java
- src/main/java/dao/OrdersDao.java
- src/main/java/vo/CustomerAddress.java
- src/main/webapp/WEB-INF/view/customerAddress/customerAddressList.jsp
- src/main/webapp/WEB-INF/view/customerAddress/modifyCustomerAddress.jsp
- src/main/webapp/WEB-INF/view/orders/ordersOne.jsp
customerAddress vo 수정, GET 리스트, Modify 수정 / ordersDao 쿼리 수정 / ordersOne 수정
> customerAddress vo 수정, GET 리스트, Modify 수정 / ordersDao 쿼리 수정 / ordersOne

- src/main/java/controller/customerAddress/AddCustomerAddressController.java
- src/main/java/controller/customerAddress/ModifyCustomerAddressController.java
- src/main/java/dao/CustomerAddressDao.java
- src/main/java/service/CustomerAddressService.java
- src/main/webapp/WEB-INF/view/customerAddress/addCustomerAddress.jsp
- src/main/webapp/WEB-INF/view/customerAddress/customerAddressList.jsp
[조영우] CustomerAddress ADD 구현 / dao, service count 기능 추가
> [조영우] CustomerAddress ADD 구현 / dao, service count 기능 추가

- src/main/webapp/WEB-INF/view/admin/goods/goodsList.jsp
- src/main/webapp/WEB-INF/view/admin/goods/goodsOne.jsp
[조영우] goods 리스트, 상세보기 - 직원,고객 뷰 각각 생성
> [조영우] goods 리스트, 상세보기 - 직원,고객 뷰 각각 생성

- src/main/java/controller/admin/goods/AddGoodsController.java
- src/main/java/controller/admin/goods/GoodsListByAdminController.java
- src/main/java/controller/admin/goods/GoodsOneByAdminController.java
- src/main/java/controller/admin/goods/ModifyGoodsController.java
- src/main/java/controller/admin/goods/RemoveGoodsController.java
- src/main/java/controller/customerAddress/AddCustomerAddressController.java
- src/main/java/controller/customerAddress/CustomerAddressListController.java
- src/main/java/controller/customerAddress/ModifyCustomerAddressController.java
- src/main/java/controller/goods/GoodsListController.java
- src/main/java/controller/goods/GoodsOneController.java
- src/main/java/controller/orders/OrdersListController.java
- src/main/java/controller/orders/OrdersOneController.java
- src/main/java/controller/orders/RemoveOrdersController.java
- src/main/java/controller/pointHistory/PointHistoryListController.java
- src/main/java/dao/OrdersDao.java
- src/main/java/service/OrdersService.java
- src/main/webapp/WEB-INF/view/admin/goods/addGoods.jsp
- src/main/webapp/WEB-INF/view/orders/removeOrders.jsp
[조영우] 주문 취소 기능 구현 / 세션 검사, 유효성 검사 수정
> [조영우] 주문 취소 기능 구현 / 세션 검사, 유효성 검사 수정

- src/main/java/controller/admin/goods/AddGoodsController.java
- src/main/java/controller/admin/goods/GoodsListByAdminController.java
- src/main/java/controller/admin/goods/ModifyGoodsController.java
- src/main/java/controller/customerAddress/AddCustomerAddressController.java
- src/main/java/controller/goods/GoodsListController.java
- src/main/java/controller/orders/RemoveOrdersController.java
- src/main/java/controller/question/RemoveQuestionController.java
- src/main/java/dao/CustomerAddressDao.java
- src/main/java/dao/GoodsCategoryDao.java
- src/main/java/dao/GoodsDao.java
- src/main/java/dao/OrdersDao.java
- src/main/java/service/CustomerAddressService.java
- src/main/java/service/GoodsCategoryService.java
- src/main/java/service/GoodsService.java
- src/main/webapp/WEB-INF/view/admin/goods/addGoods.jsp
- src/main/webapp/WEB-INF/view/admin/goods/goodsListByAdmin.jsp
- src/main/webapp/WEB-INF/view/admin/goods/modifyGoods.jsp
- src/main/webapp/WEB-INF/view/goods/goodsList.jsp
- src/main/webapp/WEB-INF/view/orders/ordersList.jsp
- src/main/webapp/WEB-INF/view/orders/removeOrders.jsp
- src/main/webapp/WEB-INF/view/question/removeQuestion.jsp
상품 카테고리별 출력 / 문의사항, 주문 내역 비밀번호 없이 삭제 가능 / 고객 주소 추가 1개 이상 가능, 출력은 5개만
> 상품 카테고리별 출력 / 문의사항, 주문 내역 비밀번호 없이 삭제 가능 / 고객 주소 추가 1개 이상 가능, 출력은 5개만

- src/main/java/controller/customerAddress/AddCustomerAddressController.java
- src/main/java/controller/customerAddress/ModifyCustomerAddressController.java
- src/main/webapp/WEB-INF/view/customerAddress/modifyCustomerAddress.jsp
- src/main/webapp/WEB-INF/view/orders/ordersList.jsp
[조영우] orders 주문 내역 날짜별 묶어서 보기 / customer_address MODIFY 수정
> [조영우] orders 주문 내역 날짜별 묶어서 보기 / customer_address MODIFY 수정

- src/main/java/controller/admin/goods/AddGoodsController.java
- src/main/java/controller/admin/goods/GoodsListByAdminController.java
- src/main/java/controller/admin/goods/GoodsOneByAdminController.java
- src/main/java/controller/admin/goods/ModifyGoodsController.java
- src/main/java/controller/admin/goods/RemoveGoodsController.java
- src/main/java/controller/orders/OrdersOneController.java
- src/main/java/controller/question/ModifyQuestionController.java
- src/main/java/controller/question/QuestionListController.java
- src/main/java/dao/GoodsDao.java
- src/main/java/service/GoodsService.java
- src/main/webapp/WEB-INF/view/admin/goods/addGoods.jsp
- src/main/webapp/WEB-INF/view/admin/goods/modifyGoods.jsp
- src/main/webapp/WEB-INF/view/admin/goods/removeGoods.jsp
- src/main/webapp/WEB-INF/view/customerAddress/addCustomerAddress.jsp
- src/main/webapp/WEB-INF/view/customerAddress/modifyCustomerAddress.jsp
- src/main/webapp/WEB-INF/view/orders/removeOrders.jsp
- src/main/webapp/WEB-INF/view/question/addQuestion.jsp
- src/main/webapp/WEB-INF/view/question/modifyQuestion.jsp
- src/main/webapp/WEB-INF/view/question/questionList.jsp
- src/main/webapp/WEB-INF/view/question/removeQuestion.jsp
[조영우] JS 자바스크립트 goods, customerAddress, orders, question 폼 유효성 검사
> [조영우] JS 자바스크립트 goods, customerAddress, orders, question 폼 유효성 검사

- src/main/java/controller/admin/goods/GoodsListByAdminController.java
- src/main/java/controller/goods/GoodsListController.java
- src/main/java/controller/question/AddQuestionController.java
- src/main/java/controller/question/QuestionOneController.java
- src/main/java/dao/GoodsCategoryDao.java
- src/main/java/dao/GoodsDao.java
- src/main/java/service/GoodsCategoryService.java
- src/main/java/service/GoodsService.java
- src/main/webapp/WEB-INF/view/admin/goods/goodsListByAdmin.jsp
- src/main/webapp/WEB-INF/view/goods/goodsList.jsp
- src/main/webapp/WEB-INF/view/orders/ordersList.jsp
- src/main/webapp/WEB-INF/view/orders/ordersOne.jsp
- src/main/webapp/WEB-INF/view/orders/removeOrders.jsp
- src/main/webapp/WEB-INF/view/pointHistory/pointHistoryList.jsp
- src/main/webapp/WEB-INF/view/question/addQuestion.jsp
- src/main/webapp/WEB-INF/view/question/modifyQuestion.jsp
- src/main/webapp/WEB-INF/view/question/questionList.jsp
- src/main/webapp/WEB-INF/view/question/questionOne.jsp
- src/main/webapp/WEB-INF/view/question/removeQuestion.jsp
[조영우] CSS 부트스트랩5 템플릿 orders, question 적용 / Question ADD 수정 / goodsCategory dao, service 수정
> [조영우] CSS 부트스트랩5 템플릿 orders, question 적용 / Question ADD 수정 /

- src/main/java/controller/admin/goods/GoodsListByAdminController.java
- src/main/java/controller/goods/GoodsListController.java
- src/main/java/dao/GoodsDao.java
- src/main/java/service/GoodsService.java
- src/main/webapp/WEB-INF/view/admin/goods/goodsListByAdmin.jsp
- src/main/webapp/WEB-INF/view/admin/goods/goodsOneByAdmin.jsp
- src/main/webapp/WEB-INF/view/goods/goodsList.jsp
- src/main/webapp/WEB-INF/view/goods/goodsOne.jsp
[조영우] goods 검색 기능 추가 dao, service 수정 / goodsOne, goodsList 세부사항 수정
> [조영우] goods 검색 기능 추가 dao, service 수정 / goodsOne, goodsList 세부사항 수정

- src/main/java/dao/GoodsDao.java
- src/main/webapp/WEB-INF/view/admin/goods/goodsOneByAdmin.jsp
- src/main/webapp/WEB-INF/view/goods/goodsOne.jsp
- src/main/webapp/WEB-INF/view/inc/footer.jsp
[조영우] goods 리스트 리뷰순 검색 추가 / footer 생성 / 빵 상세설명 추가
> [조영우] goods 리스트 리뷰순 검색 추가 / footer 생성 / 빵 상세설명 추가

- src/main/java/controller/IndexController.java
- src/main/webapp/WEB-INF/view/index.jsp
[조영우] index 페이지 생성 / index view, controller 추가
> [조영우] index 페이지 생성 / index view, controller 추가

- src/main/java/controller/admin/goods/GoodsListByAdminController.java
- src/main/java/controller/admin/goods/GoodsOneByAdminController.java
- src/main/webapp/WEB-INF/view/admin/goods/goodsListByAdmin.jsp
- src/main/webapp/WEB-INF/view/admin/goods/modifyGoods.jsp
- src/main/webapp/WEB-INF/view/admin/goods/removeGoods.jsp
- src/main/webapp/WEB-INF/view/orders/ordersList.jsp
[조영우] 사진 액박 수정, 주문 목록 수정, 상품 목록 페이징 수정 중
> [조영우] 사진 액박 수정, 주문 목록 수정, 상품 목록 페이징 수정 중
